config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  
#  get "/admin" => "admin/books#index"
  
#  namespace :admin do
#    resources :books
#  end
  
  get 'relationships/followings'
  get 'relationships/followers'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'
#  devise_for :usersの代わりに以下３行。usersのregistrationscontrollerを参照するように
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
#  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'

  resources :books do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "/search" => "searches#search"
  # get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'
  
end




                              #     Prefix Verb   URI Pattern                                                                                       Controller#Action
                              #       root GET    /                                                                                                 homes#top
                              # home_about GET    /home/about(.:format)                                                                             homes#about
                              #     books GET    /books(.:format)                                                                                  books#index
                              #           POST   /books(.:format)                                                                                  books#create
                              # edit_book GET    /books/:id/edit(.:format)                                                                         books#edit
                              #       book GET    /books/:id(.:format)                                                                              books#show
                              #           PATCH  /books/:id(.:format)                                                                              books#update
                              #           PUT    /books/:id(.:format)                                                                              books#update
                              #           DELETE /books/:id(.:format)                                                                              books#destroy
                              #     users GET    /users(.:format)                                                                                  users#index
                              # edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
                              #       user GET    /users/:id(.:format)                                                                              users#show
                              #           PATCH  /users/:id(.:format)                                                                              users#update
                              #           PUT    /users/:id(.:format)                                                                              users#update
                              
                #        new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
                #             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
                #     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
                #       new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
                #       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
                #           user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
                #                         PUT    /users/password(.:format)                                                                         devise/passwords#update
                #                         POST   /users/password(.:format)                                                                         devise/passwords#create
                # cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
                #   new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
                #   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
                #       user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
                #                         PUT    /users(.:format)                                                                                  devise/registrations#update
                #                         DELETE /users(.:format)                                                                                  devise/registrations#destroy
                #                         POST   /users(.:format)                                                                                  devise/registrations#create
                
                # book_favorite DELETE /books/:book_id/favorite(.:format)                                                                favorites#destroy
                #               POST   /books/:book_id/favorite(.:format)                                                                favorites#create
                
            # book_book_comment DELETE /books/:book_id/book_comment(.:format)                                                            book_comments#destroy
                            #   POST   /books/:book_id/book_comment(.:format)                                                            book_comments#create
                            
                    # user_relationships DELETE /users/:user_id/relationships(.:format)                                                           relationships#destroy
                    #                     POST   /users/:user_id/relationships(.:format)                                                           relationships#create
                    #     user_followings GET    /users/:user_id/followings(.:format)                                                              relationships#followings
                    #       user_followers GET    /users/:user_id/followers(.:format)                                                               relationships#followers
                    
                        # search GET    /search(.:format)                                                                                 searches#search
                        
              # messages POST           /messages(.:format)                 messages#create
                    # rooms POST        /rooms(.:format)                    rooms#create
                      # room GET        /rooms/:id(.:format)                rooms#show

#  homes_guest_sign_in POST   /homes/guest_sign_in(.:format)                            homes#new_guest

  #      new_admin_session GET    /admins/sign_in(.:format)                                                                         admins/sessions#new
#            admin_session POST   /admins/sign_in(.:format)                                                                         admins/sessions#create
#    destroy_admin_session DELETE /admins/sign_out(.:format)                                                                        admins/sessions#destroy
 #      new_admin_password GET    /admins/password/new(.:format)                                                                    admins/passwords#new
      #edit_admin_password GET    /admins/password/edit(.:format)                                                                   admins/passwords#edit
      #     admin_password PATCH  /admins/password(.:format)                                                                        admins/passwords#update
       #                   PUT    /admins/password(.:format)                                                                        admins/passwords#update
       #                   POST   /admins/password(.:format)                                                                        admins/passwords#create
#cancel_admin_registration GET    /admins/cancel(.:format)                                                                          admins/registrations#cancel

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def get_profile_image(width, height)
    # (profile_image.attached?) ? profile_image : 'no_image.jpg'
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image-icon.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no-image-icon.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # def self.looks(search, word)
  #   if search == "perfect_match"
  #     @user = User.where("name LIKE?", "#{word}")
  #   elsif search == "forward_match"
  #     @user = User.where("name LIKE?", "#{word}%")
  #   elsif search == "backward_match"
  #     @user = User.where("name LIKE?", "%#{word}")
  #   elsif search == "partial_match"
  #     @user = User.where("name LIKE?", "%#{word}%")
  #   else
  #     @user = User.all
  #   end
  # end
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  #sessions_contoroller長いのでmethod化。クラスmethodなのでself.
  def self.guest
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      # ゲストユーザー作製に必要な情報↓name,pw
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
    end
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_action :check_guest, only: :destroy

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end

end

# <!--ゲストユーザーが削除できないようにした。用意していないが。-->

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController


  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  
end


#  以下は長い。コントローラーは短く。できるところをモデルで定義する。guestというmethodにする。
#  def guest_sign_in
#    user = User.find_or_create_by(email: 'guest@example.com') do |user|
#       ゲストユーザー作製に必要な情報↓name,pw
#      user.password = SecureRandom.urlsafe_base64
#      user.name = "guest"
#    end
#   sign_in user
#   redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
#  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
    
    # ここからユーザー同士のDMルーム機能について。
    @currentUserEntry = Entry.where(user_id: current_user.id)    #roomがcreateされたら現在のユーザーと
    @userEntry = Entry.where(user_id: @user.id)                  #「チャットへボタンを押された」ユーザー両方をEntriesテーブルに記録する。
    unless @user.id == current_user.id                  # ログインしているユーザーではないこと
      @currentUserEntry.each do |cu|                    
        @userEntry.each do |u|                          # 
          if cu.room_id == u.room_id then               # true:すでにroomが作成されているならば、使いたい
            @isRoom = true                              # Entireテーブル内にあるroom_idが共通のユーザーに対して
            @roomID = cu.room_id                        # ←この変数を指定。
          end
        end
      end
      unless @isRoom                                    # false:あたらしくroom作成して、使いたい
        @room = Room.new
        @entry = Entry.new                                # Entryテーブルを作成、記録。
      end
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <% unless user == current_user %>
        <!--if文で if user != current_user も同じ意味-->
          <td>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          </td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table', style="table-layout:fixed;width:100%;">
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th style="word-wrap:break-word;"><%= user.introduction %></th>  <!--文字の折り返しが必要だったため追記。line1も併せて。-->
  </tr>

    <tr>
      <th>follows</th>
      <th>
        <%= link_to user_followings_path(user) do %>
          <%= user.followings.count %>
        <% end %>
        </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <%= link_to user_followers_path(user) do %>
          <%= user.followers.count %>
        <% end %>
      </th>
    </tr>

</table>

<div class="row">
  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>

      <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
        <%= link_to message_path(user.id),class: 'btn btn-success' do %>
          <i class="far fa-comments"></i>
        <% end %>
      <% end %>

    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    
    <div class='col-md-8 offset-md-1'>  
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, books: @books, book_new: @book_new, room: @room,
          entry: @entry, currentUserEntry: @currentUserEntry, userEntry: @userEntry, isRoom: @isRoom, roomId: @roomId %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %> <!-- comment_display:false-->
      
    </div>
  </div>
</div>