config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  
#  get "/admin" => "admin/books#index"
  
#  namespace :admin do
#    resources :books
#  end
  
  get 'relationships/followings'
  get 'relationships/followers'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'
#  devise_for :usersの代わりに以下３行。usersのregistrationscontrollerを参照するように
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
#  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'

  resources :books do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "/search" => "searches#search"
  # get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'
  
end




                              #     Prefix Verb   URI Pattern                                                                                       Controller#Action
                              #       root GET    /                                                                                                 homes#top
                              # home_about GET    /home/about(.:format)                                                                             homes#about
                              #     books GET    /books(.:format)                                                                                  books#index
                              #           POST   /books(.:format)                                                                                  books#create
                              # edit_book GET    /books/:id/edit(.:format)                                                                         books#edit
                              #       book GET    /books/:id(.:format)                                                                              books#show
                              #           PATCH  /books/:id(.:format)                                                                              books#update
                              #           PUT    /books/:id(.:format)                                                                              books#update
                              #           DELETE /books/:id(.:format)                                                                              books#destroy
                              #     users GET    /users(.:format)                                                                                  users#index
                              # edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
                              #       user GET    /users/:id(.:format)                                                                              users#show
                              #           PATCH  /users/:id(.:format)                                                                              users#update
                              #           PUT    /users/:id(.:format)                                                                              users#update
                              
                #        new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
                #             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
                #     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
                #       new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
                #       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
                #           user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
                #                         PUT    /users/password(.:format)                                                                         devise/passwords#update
                #                         POST   /users/password(.:format)                                                                         devise/passwords#create
                # cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
                #   new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
                #   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
                #       user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
                #                         PUT    /users(.:format)                                                                                  devise/registrations#update
                #                         DELETE /users(.:format)                                                                                  devise/registrations#destroy
                #                         POST   /users(.:format)                                                                                  devise/registrations#create
                
                # book_favorite DELETE /books/:book_id/favorite(.:format)                                                                favorites#destroy
                #               POST   /books/:book_id/favorite(.:format)                                                                favorites#create
                
            # book_book_comment DELETE /books/:book_id/book_comment(.:format)                                                            book_comments#destroy
                            #   POST   /books/:book_id/book_comment(.:format)                                                            book_comments#create
                            
                    # user_relationships DELETE /users/:user_id/relationships(.:format)                                                           relationships#destroy
                    #                     POST   /users/:user_id/relationships(.:format)                                                           relationships#create
                    #     user_followings GET    /users/:user_id/followings(.:format)                                                              relationships#followings
                    #       user_followers GET    /users/:user_id/followers(.:format)                                                               relationships#followers
                    
                        # search GET    /search(.:format)                                                                                 searches#search
                        
              # messages POST           /messages(.:format)                 messages#create
                    # rooms POST        /rooms(.:format)                    rooms#create
                      # room GET        /rooms/:id(.:format)                rooms#show

#  homes_guest_sign_in POST   /homes/guest_sign_in(.:format)                            homes#new_guest

  #      new_admin_session GET    /admins/sign_in(.:format)                                                                         admins/sessions#new
#            admin_session POST   /admins/sign_in(.:format)                                                                         admins/sessions#create
#    destroy_admin_session DELETE /admins/sign_out(.:format)                                                                        admins/sessions#destroy
 #      new_admin_password GET    /admins/password/new(.:format)                                                                    admins/passwords#new
      #edit_admin_password GET    /admins/password/edit(.:format)                                                                   admins/passwords#edit
      #     admin_password PATCH  /admins/password(.:format)                                                                        admins/passwords#update
       #                   PUT    /admins/password(.:format)                                                                        admins/passwords#update
       #                   POST   /admins/password(.:format)                                                                        admins/passwords#create
#cancel_admin_registration GET    /admins/cancel(.:format)                                                                          admins/registrations#cancel

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  # has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # def self.looks(search, word)
  #   if search == "perfect_match"
  #     @book = Book.where("title LIKE?", "#{word}")
  #   elsif search == "forward_match"
  #     @book = Book.where("title LIKE?", "#{word}%")
  #   elsif search == "backward_match"
  #     @book = Book.where("title LIKE?", "%#{word}")
  #   elsif search == "partial_match"
  #     @book = Book.where("title LIKE?", "%#{word}%")
  #   else
  #     @book = Book.all
  #   end
  # end
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+ content)
    else
      Book.where('title LIKE ?', '%' + content + '%')
    end
  end
  
  
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
    @books = Book.all
    
    current_user.view_counts.create(book_id: @book.id)
  end

  def index
#    @books = Book.all
    @book = Book.new
    @user = current_user
    @book_comment = BookComment.new
    
    # 過去一週間で
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    # いいねされた数が多い順
    @books = Book.includes(:favorites).sort_by {|x| x.favorites.where(created_at: from...to).size}.reverse
   
    # @books = Book.includes(:favorited_users).
    #   sort_by {|x|
    #     x.favorited_users.includes(:favorites).where(created_at: from...to).size
    #   }.reverse
      # sort {|a,b|
      #   a.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
      #   b.favorited_users.includes(:favorotes).where(created_at: from...to).size
      # }.reverse
    current_user.view_counts.create(book_id: @book.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
      # @book = Book.find(params[:id])
    
  end

  def update
    # @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
  
  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
  
end

app/helpers/admins/books_helper.rb
module Admins::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: Book.new, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <!--%= image_tag book.user.get_profile_image, size:'50x50' %>-->
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>" >
          <%= render "favorites/favorite", book: book %>
        </td>
        <td>
          <!--% if comment_display %>-->
            <p>コメント数：<%= book.book_comments.count %></p>
          <!--% end %>-->
        </td>
        <td>
          閲覧数：<%= book.view_counts.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @book %>
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @book %>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form' %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      
      
      <%= render 'books/index', books: @books %><!--comment_display:true-->
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>

    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' , user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form' %>
    </div>

    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>

          <td id="favorite_btn_<%= @book.id %>" >
            <%= render "favorites/favorite", book: @book %>
          </td>

<!--このコメント数も非同期通信化したい-->
          <td id="comment_count">
            <%= render "book_comments/count", book: @book %>
            <!--<p>コメント数：%= @book.book_comments.count %></p>-->
          </td>

          <td>閲覧数：<%= @book.view_counts.count %></td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>

<!--ここからコメント一覧-->
      <div id="comment_index">
        <%= render "book_comments/index", book: @book %>
      </div>

      <%= render 'layouts/errors', obj: @book_comment %>


<!--コメントのフォーム-->
      <div id="comment_form">
        <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      </div>

      
      
    </div>

  </div>
</div>