config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    # ↓ローカルに追加されたコントローラーを参照する(コントローラー名: "コントローラーの参照先")
    registrations: "admins/registrations",
    sessions: "admins/sessions",
    passwords: "admins/passwords",
    confirmations: "admins/confirmations"
  }
  
#  get "/admin" => "admin/books#index"
  
#  namespace :admin do
#    resources :books
#  end
  
  get 'relationships/followings'
  get 'relationships/followers'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'
#  devise_for :usersの代わりに以下３行。usersのregistrationscontrollerを参照するように
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
#  post 'homes/guest_sign_in', to: 'homes#guest_sign_in'

  resources :books do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "/search" => "searches#search"
  # get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'messages/:id' => 'messages#message', as: 'message'
  post 'messages' => 'messages#create', as: 'messages'
  
end




                              #     Prefix Verb   URI Pattern                                                                                       Controller#Action
                              #       root GET    /                                                                                                 homes#top
                              # home_about GET    /home/about(.:format)                                                                             homes#about
                              #     books GET    /books(.:format)                                                                                  books#index
                              #           POST   /books(.:format)                                                                                  books#create
                              # edit_book GET    /books/:id/edit(.:format)                                                                         books#edit
                              #       book GET    /books/:id(.:format)                                                                              books#show
                              #           PATCH  /books/:id(.:format)                                                                              books#update
                              #           PUT    /books/:id(.:format)                                                                              books#update
                              #           DELETE /books/:id(.:format)                                                                              books#destroy
                              #     users GET    /users(.:format)                                                                                  users#index
                              # edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
                              #       user GET    /users/:id(.:format)                                                                              users#show
                              #           PATCH  /users/:id(.:format)                                                                              users#update
                              #           PUT    /users/:id(.:format)                                                                              users#update
                              
                #        new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
                #             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
                #     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
                #       new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
                #       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
                #           user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
                #                         PUT    /users/password(.:format)                                                                         devise/passwords#update
                #                         POST   /users/password(.:format)                                                                         devise/passwords#create
                # cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
                #   new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
                #   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
                #       user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
                #                         PUT    /users(.:format)                                                                                  devise/registrations#update
                #                         DELETE /users(.:format)                                                                                  devise/registrations#destroy
                #                         POST   /users(.:format)                                                                                  devise/registrations#create
                
                # book_favorite DELETE /books/:book_id/favorite(.:format)                                                                favorites#destroy
                #               POST   /books/:book_id/favorite(.:format)                                                                favorites#create
                
            # book_book_comment DELETE /books/:book_id/book_comment(.:format)                                                            book_comments#destroy
                            #   POST   /books/:book_id/book_comment(.:format)                                                            book_comments#create
                            
                    # user_relationships DELETE /users/:user_id/relationships(.:format)                                                           relationships#destroy
                    #                     POST   /users/:user_id/relationships(.:format)                                                           relationships#create
                    #     user_followings GET    /users/:user_id/followings(.:format)                                                              relationships#followings
                    #       user_followers GET    /users/:user_id/followers(.:format)                                                               relationships#followers
                    
                        # search GET    /search(.:format)                                                                                 searches#search
                        
              # messages POST           /messages(.:format)                 messages#create
                    # rooms POST        /rooms(.:format)                    rooms#create
                      # room GET        /rooms/:id(.:format)                rooms#show

#  homes_guest_sign_in POST   /homes/guest_sign_in(.:format)                            homes#new_guest

  #      new_admin_session GET    /admins/sign_in(.:format)                                                                         admins/sessions#new
#            admin_session POST   /admins/sign_in(.:format)                                                                         admins/sessions#create
#    destroy_admin_session DELETE /admins/sign_out(.:format)                                                                        admins/sessions#destroy
 #      new_admin_password GET    /admins/password/new(.:format)                                                                    admins/passwords#new
      #edit_admin_password GET    /admins/password/edit(.:format)                                                                   admins/passwords#edit
      #     admin_password PATCH  /admins/password(.:format)                                                                        admins/passwords#update
       #                   PUT    /admins/password(.:format)                                                                        admins/passwords#update
       #                   POST   /admins/password(.:format)                                                                        admins/passwords#create
#cancel_admin_registration GET    /admins/cancel(.:format)                                                                          admins/registrations#cancel

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @model = params[:model]
    @content = params[:content]
    @method = params[:method]
    
    if @model == "user"
      @records = User.search_for(@content, @method)
      # @users = User.looks(params[:search], params[:word])
      # render "/searches/search"
    else
      @records = Book.search_for(@content, @method)
      # @books = Book.looks(params[:search], params[:word])
      # render "/searches/search"
    end
  
  
    # respond_to do |format|
    #   format.html # この行が必要です
    # end
    
    # render 'search_for'
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-8 offset-md-4 mt-2'>
      <% if user_signed_in? %>
      
        <%= form_with url: search_path, local: true, method: :get do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
          <%= f.submit "検索", class: "btn btn-primary" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/searches/search.html.erb
<!--<table class="table table-hover table-inverse">-->
  <% if @model == "user" %>
    <h2>Users search for "<%= @content %>"</h2>
    <%= render 'users/index', users: @records %>
      <!--<thead>-->
      <!--  <tr>-->
      <!--    <th>iamge</th>-->
      <!--    <th>name</th>-->
      <!--    <th colspan="3"></th>-->
      <!--  </tr>-->
      <!--</thead>-->
      <!--<tbody>-->
      <!--  % @users.each do |user| %>-->
      <!--    <tr>-->
      <!--      <td>%= image_tag user.get_profile_image(50,50) %></td>-->
      <!--      <td>%= user.name %></td>-->
      <!--    </tr>-->
      <!--</tbody>-->
  <% elsif @model == "book" %>
    <h2>Books search for "<%= @content %>"</h2>
    <%= render 'books/index', books: @records %>
      <!--<thead>-->
      <!--  <tr>-->
      <!--    <th></th>-->
      <!--    <th>Title</th>-->
      <!--    <th>opinion</th>-->
      <!--  </tr>-->
      <!--</thead>-->
      <!--<tbody>-->
      <!--  % @books.each do |book| %>-->
      <!--    <tr>-->
      <!--      <td>-->
      <!--        %= link_to user_path(book.user) do %>-->
      <!--          %= image_tag book.user.get_profile_image(50,50) %>-->
      <!--        % end %>-->
      <!--      </td>-->
      <!--      <td>-->
      <!--        %= link_to book.title, book_path(book.id) %>-->
      <!--      </td>-->
      <!--      <td>%= book.body %></td>-->
      <!--    </tr>-->
      <!--  % end %>-->
      <!--</tbody>-->
  <% end %>
  
<!--</table>-->

app/views/searches/search_for.html.erb
<table class="table table-hover table-inverse">
  <% if @range == "User" %>
    <h2>Users search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th>iamge</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image(50,50) %></td>
          <td><%= user.name %></td>
        </tr>
    </tbody>
  <% else %>
    <h2>Books search for "<%= @word %>"</h2>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(50,50) %>
            <% end %>
          </td>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
  
</table>